[global]
developmentMode = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#ff416c"
backgroundColor = "#0f0c29"
secondaryBackgroundColor = "#302b63"
textColor = "#ffffff" 